import { defineTokens } from "@pandacss/dev";
import { colors } from "./colors";

export const tokens = defineTokens({
  fontSizes: {
    xs: { value: ".75rem" },
    sm: { value: ".875rem" },
    base: { value: "1rem" },
    lg: { value: "1.125rem" },
    xl: { value: "1.25rem" },
    "2xl": { value: "1.5rem" },
    "3xl": { value: "1.875rem" },
    "4xl": { value: "2.25rem" },
    "5xl": { value: "3rem" },
    "6xl": { value: "4rem" },
  },
  sizes: {
    xs: { value: "0.75rem" },
    sm: { value: "0.875rem" },
    base: { value: "1rem" },
    lg: { value: "1.125rem" },
    xl: { value: "1.25rem" },
    "2xl": { value: "1.5rem" },
    "3xl": { value: "1.875rem" },
    "4xl": { value: "2.25rem" },
    "5xl": { value: "3rem" },
    "6xl": { value: "4rem" },
  },
  fontWeights: {
    thin: { value: 100 },
    extralight: { value: 200 },
    light: { value: 300 },
    normal: { value: 400 },
    medium: { value: 500 },
    semibold: { value: 600 },
    bold: { value: 700 },
    extrabold: { value: 800 },
    black: { value: 900 },
  },
  fontStyles: {
    normal: { value: "normal" },
    italic: { value: "italic" },
  },
  fonts: {
    // noto: { value: "var(--font-noto-sans), sans-serif" },
  },
  radii: {
    xs: { value: ".125rem" },
    sm: { value: ".25rem" },
    base: { value: ".375rem" },
    lg: { value: ".5rem" },
    xl: { value: ".75rem" },
    "2xl": { value: "1rem" },
    "3xl": { value: "1.5rem" },
    "4xl": { value: "2rem" },
    "5xl": { value: "3rem" },
    "6xl": { value: "4rem" },
  },
  spacing: {
    0: { value: "0" },
    0.5: { value: ".125rem" },
    1: { value: ".25rem" },
    1.5: { value: ".375rem" },
    2: { value: ".5rem" },
    2.5: { value: ".625rem" },
    3: { value: ".75rem" },
    3.5: { value: ".875rem" },
    4: { value: "1rem" },
  },
  colors,
});
