import { component$ } from "@builder.io/qwik";
import { Image } from "~/components/image/image";
import { css } from "~/styled-system/css";
import { useTranslate } from "qwik-speak";
import { MdiApi } from "~/components/icon/icon";

export const ArtifactsSection = component$(() => {
  const t = useTranslate();
  return (
    <section>
      <h2>{t("top.artifacts")}</h2>
      <h3>{t("top.main")}</h3>
      <div
        class={css({
          display: "grid",
          gridTemplateAreas: `
          "book chrome"
          "book bochi"`,
          gridTemplateColumns: "1fr 1fr",
          gridTemplateRows: "auto auto",
          lg: {
            width: "640px",
          },
        })}
      >
        <div
          class={css({
            gridArea: "book",
            borderColor: "bg.quote",
            borderWidth: "1px",
            borderRadius: "4px",
            _hover: {
              borderColor: "text.link",
            },
          })}
        >
          <Image
            src="https://res.cloudinary.com/silverbirder/image/upload/v1696334257/silver-birder.github.io/artifacts/Introduction-to-webcomponents-for-beginners.jpg"
            width={1057 / 3}
            height={1500 / 3}
            layout="constrained"
            alt={t("top.introToWebComponentsForBeginners")}
            href="https://www.amazon.co.jp/gp/product/B08CY2QCFV/"
          />
        </div>
        <div
          class={css({
            gridArea: "chrome",
            borderColor: "bg.quote",
            borderWidth: "1px",
            borderRadius: "4px",
            _hover: {
              borderColor: "text.link",
            },
          })}
        >
          <Image
            src="https://res.cloudinary.com/silverbirder/image/upload/v1696643993/silver-birder.github.io/artifacts/ai-ghost-writer-logo.png"
            width={2000 / 3}
            height={1500 / 3}
            layout="constrained"
            alt={t("top.aiGhostWriter")}
            href="https://chrome.google.com/webstore/detail/ai-ghostwriter/hpcokeldeijnfmbbbjkedhnedjjbjmoa"
          />
        </div>
        <div
          class={css({
            gridArea: "bochi",
            borderColor: "bg.quote",
            borderWidth: "1px",
            borderRadius: "4px",
            _hover: {
              borderColor: "text.link",
            },
          })}
        >
          <Image
            src="https://res.cloudinary.com/silverbirder/image/upload/v1707629480/silver-birder.github.io/artifacts/bochi-bochi.png"
            width={1500 / 5}
            height={1500 / 5}
            layout="constrained"
            alt={t("top.bochi")}
            href="https://bochi-bochi.vercel.app"
          />
        </div>
      </div>
      <h3>{t("top.others")}</h3>
      <ul>
        <li>
          <a
            href="https://www.webcomponents.org/element/silverbirder/o-embed"
            target="_brank"
          >
            o-embed - webcomponents.org
          </a>
          <ul>
            <li>o-embed is Web Components for oEmbed generated by open-wc</li>
          </ul>
        </li>
        <li>
          <a
            href="https://www.webcomponents.org/element/silverbirder/ogp-me"
            target="_brank"
          >
            ogp-me - webcomponents.org
          </a>
          <ul>
            <li>
              ogp-me is a WebComponent that displays Facebook-like information
              based on Open Graph Protocol (OGP)
            </li>
          </ul>
        </li>
        <li>
          <a
            href="https://github.com/silverbirder/Google-Account-Photo-API"
            target="_brank"
          >
            Google Account Photo API - GitHub
          </a>
          <ul>
            <li>
              Google Account Photo API just returns the image of your Google
              account
            </li>
          </ul>
        </li>
        <li>
          <a href="https://github.com/silverbirder/CaAT" target="_brank">
            CaAT - GitHub
          </a>
          <ul>
            <li>
              CaAT is the Google Apps Script Library that Calculate the Assigned
              Time in Google Calendar
            </li>
          </ul>
        </li>
        <li>
          <a href="https://github.com/silverbirder/Cotlin" target="_brank">
            Cotlin - GitHub
          </a>
          <ul>
            <li>
              Cotlin is tools that collect links in tweet by using the Twitter
              API(Search Tweets)
            </li>
          </ul>
        </li>
        <li>
          <a href="https://github.com/silverbirder/rMinc" target="_brank">
            rMinc - GitHub
          </a>
          <ul>
            <li>
              rMinc is the Google Apps Script Library that register Mail in
              Calendar
            </li>
          </ul>
        </li>
        <li>
          <a href="https://github.com/silverbirder/tiqav2" target="_brank">
            tiqav2 - GitHub
          </a>
          <ul>
            <li>Tiqav2 is the platform that provide image search API</li>
          </ul>
        </li>
        <li>
          <a
            href="https://github.com/silverbirder/zoom-meeting-creator"
            target="_brank"
          >
            zoom-meeting-creator - GitHub
          </a>
          <ul>
            <li>
              zoom-meeting-creator is a Google Apps Script for creating zoom
              meetings
            </li>
          </ul>
        </li>
      </ul>
    </section>
  );
});
